### ISSUE TITLE
Install co-pilot with brew in Cloud9?

### ISSUE THREAD

**Issue by nsubrahm-aws** [brentley/ecsworkshop#148]
The instruction to install `copilot-cli` [here](https://ecsworkshop.com/microservices/software/) refers to `brew` command. Is this intentional? 

I have my Cloud9 set-up for Ubuntu. So, I installed `copilot-cli` with the following as described [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Copilot.html).

```bash
sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
   && sudo chmod +x /usr/local/bin/copilot \
   && copilot --help
```

**Comment by brentley** [comment]
this is good, but i believe the expectation is that cloud9 is running
amazon linux which has brew available. i’m glad you were able to adapt
for your preferences though. 

On February 16, 2021, GitHub <notifications@github.com> wrote:
> The instruction to install copilot-cli here
> <https://ecsworkshop.com/microservices/software/> refers to brew
> command. Is this intentional?
>
> I have my Cloud9 set-up for Ubuntu. So, I installed copilot-cli with

> the following as described here
> <https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Copilot.html>.
>
> sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-

> cli/releases/latest/download/copilot-linux \ && sudo chmod +x
> /usr/local/bin/copilot \ && copilot --help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brentley/ecsworkshop/issues/148>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAB3SEDRXPVVAWJE63KLRWDS7H4DPANCNFSM4XVZHUAQ>.

**Comment by nsubrahm-aws** [comment]
I didn't know Amazon Linux had `brew` installed!

Now that, I have already launched an Ubuntu based Cloud9, would you know the link to session manager plugin? The workshop points to an `.rpm`. [here](https://ecsworkshop.com/microservices/platform/build_environment/).

**Comment by ohookins** [comment]
Apologies, I created #149 without checking for matching issues first - this seems to be the issue. That being said, my Cloud9 environment is indeed running Amazon Linux 2 and there is no Homebrew installation available, so at the very least we are missing a pre-requisite to install Homebrew.

**Comment by adamjkeller** [comment]
The default is now Amazon Linux 2, which doesn't have Homebrew installed by default anymore. Merged the PR as there is no other reliance on Homebrew outside of copilot. Thanks!
